# Deploys ArgoCD with anonymous admin access enabled.
# ArgoCD will be available at http://localhost:30080/
aissemble-infrastructure-chart:
  jenkins:
    enabled: false
  ingress-nginx:
    enabled: false
  argo-cd:
    crds:
      keep: false
    configs:
      cm:
        admin.enabled: false
        users.anonymous.enabled: true
      rbac:
        policy.default: "role:admin"
    server:
      ingress:
        enabled: false
      service:
        type: "NodePort"
    repoServer:
      env:
        - name: HELM_CACHE_HOME
          value: /helm-working-dir/.cache #Work around for install issue where plugins and cache locations being the same conflicts
      initContainers:
        - name: helm-plugin-install
          image: alpine/helm
          env:
            - name: HELM_PLUGINS
              value: /helm-working-dir/plugins #Configure Helm to write to the volume mount that the repo server uses
          volumeMounts:
            - mountPath: /helm-working-dir
              name: helm-working-dir
          command: [ "/bin/sh", "-c" ]
          args: # install plugin
            - apk --no-cache add curl;
              helm plugin install https://github.com/aslafy-z/helm-git --version 1.3.0;
              chmod -R 777 $HELM_PLUGINS;
